#!/usr/bin/env bash

rvm_location=$(which rvm)
if [ -f "${rvm_location}" ]; then
  rvm get stable
else
  gpg2 --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
  \curl -sSL https://get.rvm.io | bash -s stable
fi
ln -sv "${DOTFILES_HOME}/ruby/.rvm.sh" ~
source ~/.rvm.sh
cd $HOME
rvm install ruby-2.5.3
rvm use ruby-2.5.3
cd -

