#!/usr/bin/env bash                                                                                                                          
                                                                                                                                             
rm -rf ~/.rvm
rm ~/.rvmrc
rm ~/.rvm.sh
rm -rf ~/.gem

