#!/usr/bin/env bash

echo "Configuring git"
git_location=$(which git)

if [ ! -f "${git_location}" ]; then
  if [ $PLATFORM == 'Darwin' ]; then
    brew install git
  elif [ -f "$(which apt-get)" ] && [ "${SUDOER}" -eq 1 ]; then
    sudo apt-get install -y -q git
  fi
fi

if [ "$CODESPACES" == "true" ]; then
  ln -svf "${DOTFILES_HOME}/git/.gitconfig-codespaces" ~/.gitconfig
else
  ln -svf "${DOTFILES_HOME}/git/.gitconfig" ~
fi


