#!/usr/bin/env bash                                                                                                                          
                                                                                                                                             
rm ~/.vim
rm ~/.viminfo
rm ~/.vimrc

