#!/usr/bin/env bash

nvm_location=$(which nvm)
if [ ! -f "${nvm_location}" ]; then
  if [ $PLATFORM == 'Darwin' ]; then
    brew install nvm
  else
    curl https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash
  fi
fi
ln -sv "${DOTFILES_HOME}/node/.nvm.sh" ~
source ~/.nvm.sh
nvm install v12.14.1
nvm alias default v12.14.1

