#!/usr/bin/env bash                                                                                                                          
                                                                                                                                             
rm -rf ~/.nvm
rm ~/.nvm.sh
