eval "$PROFILE_THIS_FILE"

DEFAULT_USER="$(whoami)"
prompt_context(){}

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

eval $REPORT_TIME
