#!/usr/bin/env bash

PYTHON_VERSION=3.9.9

pyenv_type=$(type -t pyenv)
if [[ ! "$pyenv_type" =~ ^(file|function)$ ]]; then
  if [ $PLATFORM = 'Darwin' ]; then
    brew install pyenv
    brew install pyenv-virtualenvwrapper
  else
    git clone https://github.com/pyenv/pyenv.git ~/.pyenv
    cd ~/.pyenv
    src/configure
    make -C src
    cd -
  fi
fi
ln -sv "${DOTFILES_HOME}/python/.pyenv.sh" ~
source ~/.pyenv.sh --environment
source ~/.pyenv.sh --init
cd ~/.pyenv
git pull
cd -
if [[ "$(pyenv versions | grep -c $PYTHON_VERSION)" == "1" ]]; then
  echo "Python ${PYTHON_VERSION} already installed."
else
  pyenv install $PYTHON_VERSION
fi
pyenv global $PYTHON_VERSION
pip install --upgrade pip
pip install --upgrade pipenv

