#!/usr/bin/env bash

gpg2_location=$(which gpg2)
if [ ! -f "${gpg2_location}" ]; then
  gpg_location=$(which gpg)
  if [ ! -f "${gpg_location}" ]; then
    if [ $PLATFORM == 'Darwin' ]; then
      brew install gnupg
    elif [ -f "$(which apt-get)" ]; then
      sudo apt-get install gpg
    fi
  fi
  sudo ln -sv "$(which gpg)" "$(which gpg)2"    
fi

