#!/usr/bin/env bash

zsh_location=$(which zsh)

if [ ! -f "${zsh_location}" ]; then
  sudo apt install -y zsh
  zsh_location=$(which zsh)
fi

echo 'Configuring zsh'
sudo usermod --shell "${zsh_location}" $(whoami)
mkdir -p ~/.zsh
if [ ! -f "~/.oh-my-zsh" ]; then
  curl -L http://install.ohmyz.sh | sh
fi
ln -svf "${DOTFILES_HOME}/zsh/.zshrc" ~
ln -svf "${DOTFILES_HOME}/zsh/.zshenv" ~
ln -svf "${DOTFILES_HOME}/zsh/.zlogin" ~
ln -svf "${DOTFILES_HOME}/zsh/.iterm2_shell_integration.zsh" ~
if [ ! -f "~/.zsh/zsh-autosuggestions" ]; then
  git clone https://github.com/zsh-users/zsh-autosuggestions.git ~/.zsh/zsh-autosuggestions
fi
cd ~/.zsh/zsh-autosuggestions
git pull
cd -

