#!/usr/bin/env bash

zsh_location=$(which zsh)
if [ -f "${zsh_location}" ]; then
  echo 'Configuring zsh'
  sudo usermod --shell "${zsh_location}" $(whoami)
  if [ ! -f "~/.oh-my-zsh" ]; then
    curl -L http://install.ohmyz.sh | sh
  fi
  ln -svf "${DOTFILES_HOME}/zsh/.zshrc" ~
  ln -svf "${DOTFILES_HOME}/zsh/.iterm2_shell_integration.zsh" ~
  if [ ! -f "~/.oh-my-zsh/custom/plugins/zsh-autosuggest" ]; then
    git clone https://github.com/zsh-users/zsh-autosuggestions.git ~/.oh-my-zsh/custom/plugins/zsh-autosuggest
  fi
  cd ~/.oh-my-zsh/custom/plugins/zsh-autosuggest
  git pull
  cd -
fi
