#!/usr/bin/env bash                                                                                                                          
                                                                                                                                             
rm ~/.iterm2_shell_integration.zsh
rm -rf ~/.oh-my-zsh
rm ~/.zlogin
rm ~/.zprofile
rm ~/.zshenv
rm ~/.zshrc
rm -rf ~/.zsh
rm ~/.zsh_history
rm ~/.zcompdump-*

