# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

format = """
[](bg:black fg:white)\
[ $os $hostname](bg:white)\
[](bg:blue fg:white)\
[ $directory ](bg:blue)\
[](fg:blue bg:black)\
$git_branch\
$git_status"""

right_format = "$character $direnv $package $username"

[character]
success_symbol = '[✔](bold green)'
error_symbol = '[✗](bold red)'

[directory]
style = "bg:blue fg:bright-white"

[hostname]
style = "bg:white fg:black"
format = "[$hostname ]($style)"

[os]
disabled = false
style = "bg:white fg:black"
[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
AOSC = ""
Arch = "󰣇"
Artix = "󰣇"
EndeavourOS = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
Pop = ""

[time]
disabled = false
style = "bg:white fg:black"
format = '[$time]($style)'
time_format = '%T'
